### ISSUE TITLE
make test fails on macOS

### ISSUE THREAD

**Issue by ANGSD** [RAHenriksen/NGSNGS#34] opened 2023-09-09 07:11 UTC

**Comment by ANGSD** [comment] 2023-11-18 12:28
```
fvr124@SUN1024817 test % md5sum -c MycoBactTest.md5 
READID.txt: FAILED
CIGAR.txt: OK
SEQ.txt: FAILED
MycoBactFqPEOut_R1.fq: FAILED
MycoBactFqPEOut_R2.fq: FAILED
MycoBactFaSEOut.fa: FAILED
MycoBactFqSEPolyOut.fq: FAILED
MycoBactFqSEClOut.fq: FAILED
HaploidRef_Deletion_0.fa: OK
HaploidRes_Deletion_0.fq: FAILED
HaploidRef_Deletion_1.fa: OK
HaploidRes_Deletion_1.fq: FAILED
HaploidRef_Deletion_2.fa: OK
HaploidRes_Deletion_2.fq: FAILED
HaploidRef_Insertion_0.fa: OK
HaploidRes_Insertion_0.fq: FAILED
HaploidRef_Insertion_1.fa: OK
HaploidRes_Insertion_1.fq: FAILED
HaploidRef_Insertion_2.fa: OK
HaploidRes_Insertion_2.fq: FAILED
HaploidRef_SNP_0.fa: OK
HaploidRes_SNP_0.fq: FAILED
HaploidRef_SNP_1.fa: OK
HaploidRes_SNP_1.fq: FAILED
HaploidRef_SNP_2.fa: OK
HaploidRes_SNP_2.fq: FAILED
DiploidRef_Deletion_0.fa: OK
DiploidRes_Deletion_0.fq: FAILED
DiploidRef_Deletion_1.fa: OK
DiploidRes_Deletion_1.fq: FAILED
DiploidRef_Deletion_2.fa: OK
DiploidRes_Deletion_2.fq: FAILED
DiploidRef_Insertion_0.fa: OK
DiploidRes_Insertion_0.fq: FAILED
DiploidRef_Insertion_1.fa: OK
DiploidRes_Insertion_1.fq: FAILED
DiploidRef_Insertion_2.fa: OK
DiploidRes_Insertion_2.fq: FAILED
DiploidRef_SNP_0.fa: OK
DiploidRes_SNP_0.fq: FAILED
DiploidRef_SNP_1.fa: OK
DiploidRes_SNP_1.fq: FAILED
DiploidRef_SNP_2.fa: OK
DiploidRes_SNP_2.fq: FAILED
DelOut.fq: FAILED
InsOut.fq: FAILED
DelTmp.txt: FAILED
InsTmp.txt: FAILED
MycoBactQSLLSEOUT.fq: FAILED
md5sum: WARNING: 30 of 49 computed checksums did NOT match
fvr124@SUN1024817 test % 

```

**Comment by RAHenriksen** [comment] 2024-07-22 10:49
A lot of functionalities and parts of the code has been changed since this issue was raised, and i am not able to reproduce this issue on my mac. So please let me know if this issue persist? otherwise i will close this within the next week.

Best regards,
Rasmus

**Closed** 2024-07-22 18:00 UTC
